apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compliments-bot.fullname" . }}
  labels:
    app: {{ include "compliments-bot.name" . }}
    chart: {{ include "compliments-bot.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  SLACK_SHARED_SECRET: {{ .Values.config.SLACK_SHARED_SECRET | b64enc | quote }}
  SLACK_OAUTH_TOKEN: {{ .Values.config.SLACK_OAUTH_TOKEN | b64enc | quote }}
  SLACK_WEBHOOK: {{ .Values.config.SLACK_WEBHOOK | b64enc | quote }}