# Default values for compliments-bot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.vnerd.com/compliments-bot
  tag: master
  pullPolicy: IfNotPresent

config:
  SLACK_SHARED_SECRET: ""
  SLACK_OAUTH_TOKEN: ""
  SLACK_WEBHOOK: ""
  ERLANG_COOKIE: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 80

resources:
  limits:
   cpu: 250m
   memory: 512Mi
  requests:
   cpu: 250m
   memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
